services:
  - name: multigeth_node
    description: these are the multi-geth nodes that will be added to the testnet
    image: multigeth/multi-geth
    volumes:
      - path: /staticpeers/
        name: staticpeers
        scope: singleton
    input-files:
      - source-path: ./genesis.json
        destination-path: /geth/genesis.json
      - source-path: ./keystore/pk$_n
        destination-path: /geth/keystore/pk
      - source-path: ./keystore/pw.txt
        destination-path: /geth/pw.txt
      - source-path: ./keystore/nodekey$_n
        destination-path: /geth/nodekey
    script:
      inline: |
        cp /staticpeers/static-nodes.json /geth/static-nodes.json && geth --nousb --datadir ./geth/ init /geth/genesis.json && geth --datadir ./geth/ --rpc --nodiscover --ethstats $NAME:etc_testnet_secret@ethstats-service0:3000 --rpcaddr 0.0.0.0 --miner.gasprice=1 --rpcapi "admin,web3,db,eth,net,personal,miner,txpool" --rpccorsdomain "0.0.0.0" --txpool.nolocals --rpcvhosts=* --port 30303 --networkid 555555 --nousb --mine --minerthreads=1 --verbosity 5
  - name: ethstats
    image: gcr.io/whiteblock/ethstats:master
    environment:
      HOST: "0.0.0.0"
    input-files:
      - source-path: ws_secret.json
        destination-path: /eth-netstats/ws_secret.json
task-runners:
  - name: geth-staticpeers-helper
    description: will gather the IP addresses and generate a static peers file.
    image: "gcr.io/whiteblock/helpers/besu/staticpeers:master"
    volumes:
      - path: /staticpeers/
        name: staticpeers
        scope: singleton
    script:
      inline: ./besuStaticPeers generate -a '[{"publicKey":"04eab89943b5b2aa38745051471b31dc09d187c99b8fc6b740a8587ac43d1d65d644086a862189bc6298198453ba68076ebdb9cd7013d8893878f628a664376e"},{"publicKey":"a1ae7b1352fc0e02df6d75e90046d17fb212629a608f584760434df2375fb301ec9e55ac693a77f4bc0c3efdafec3b3853aa7cb2cb48480800ef6658f747d034"}]' --ip '["'$MULTIGETH_BOOT_NODE_SERVICE0_COMMON_NETWORK'", "'$MULTIGETH_NODES_SERVICE0_COMMON_NETWORK'"]'  >> /staticpeers/static-nodes.json
    resources:
      memory: 2 GB
tests:
  - name: start-multigeth
    description: first test - run three multigeth nodes on the common-network
    phases:
      - name: create
        tasks:
          - type: geth-staticpeers-helper
            timeout: 3 m
      - name: start
        description: start the nodes
        duration: 10 m
        system:
          - type: multigeth_nodes
            count: 2
            resources:
              networks:
                - name: common-network
          - type: ethstats
            port-mappings:
              - "80:3000"
            resources:
              networks:
                - name: common-network