services:
  - name: nginx
    image: nginx:alpine
    resources:
      memory: 500 MB
tests:
  - name: serve-static-files
    description: Serve the default static content of the nginx image.
    wait-for: 10m
    system:
      - type: nginx
        port-mappings:
          - "80:80"