services:
  - name: prysm-beacon
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest
    args:
      - --datadir=/data
      - --init-sync-no-verify
    resources:
      cpus: 2
      memory: 2 GB
      storage: 5 GiB
tests:
  - name: simple-prysm-exercise
    description: run a prysm testnet and validate some blocks
    wait-for: 10m
    system:
      - name: beacon-node-testnet
        type: prysm-beacon
        count: 4